name: Build Android APK

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to build (e.g., 1.0.0)'
        required: true
        default: '1.0.0'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'gradle'
        
    - name: Set up Android SDK
      uses: android-actions/setup-android@v2
        
    - name: Install Android SDK components
      run: |
        echo "=== Installing Android SDK Components ==="
        echo "Android SDK location: $ANDROID_HOME"
        
        # Accept licenses
        yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses
        
        # Install required components
        echo "Installing platform android-30..."
        $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "platforms;android-30"
        
        echo "Installing build tools 29.0.3..."
        $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "build-tools;29.0.3"
        
        echo "Installing platform tools..."
        $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "platform-tools"
        
        echo "=== End Installing Android SDK Components ==="
        
    - name: Verify environment
      run: |
        echo "=== Environment Verification ==="
        echo "Java version:"
        java -version
        echo "Android SDK location: $ANDROID_HOME"
        echo "Build tools available:"
        ls -la $ANDROID_HOME/build-tools/
        echo "Platforms available:"
        ls -la $ANDROID_HOME/platforms/
        echo "Testing aapt:"
        $ANDROID_HOME/build-tools/29.0.3/aapt version
        echo "=== End Environment Verification ==="
        
    - name: Make gradlew executable
      run: chmod +x gradlew
      
    - name: Test Gradle setup
      run: |
        echo "=== Gradle Setup Test ==="
        ./gradlew --version
        ./gradlew tasks --all | grep -E "(android|assemble)" | head -3
        echo "=== End Gradle Setup Test ==="
      
    - name: Build APK
      run: |
        echo "=== Building APK ==="
        ./gradlew android:assembleRelease
        echo "=== APK Build Complete ==="
      
    - name: Sign APK
      run: |
        echo "=== Signing APK ==="
        # Create keystore for signing
        keytool -genkey -v -keystore keystore.jks -keyalg RSA -keysize 2048 -validity 10000 -alias android -storepass android -keypass android -dname "CN=Android Debug,O=Android,C=US"
        
        # Sign the APK
        jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore keystore.jks android/build/outputs/apk/release/android-release-unsigned.apk android
        
        # Optimize APK
        $ANDROID_HOME/build-tools/29.0.3/zipalign -v 4 android/build/outputs/apk/release/android-release-unsigned.apk android/build/outputs/apk/release/Unlucky.apk
        
        # Verify APK was created
        ls -la android/build/outputs/apk/release/
        echo "=== APK Signing Complete ==="
      
    - name: Upload APK as artifact
      uses: actions/upload-artifact@v4
      with:
        name: Unlucky-APK
        path: android/build/outputs/apk/release/Unlucky.apk
        retention-days: 30
      
    - name: Get version
      id: get_version
      run: |
        if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
          echo "version=${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT
        else
          # Extract version from tag
          echo "version=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
        fi
        
    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: v${{ steps.get_version.outputs.version }}
        name: Release v${{ steps.get_version.outputs.version }}
        body: |
          Android APK for Unlucky game v${{ steps.get_version.outputs.version }}
          
          ## Installation
          1. Download the APK file
          2. Enable "Install from unknown sources" in your Android settings
          3. Install the APK
        files: android/build/outputs/apk/release/Unlucky.apk
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}