name: Build Android APK

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to build (e.g., 1.0.0)'
        required: true
        default: '1.0.0'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'gradle'
        
    - name: Set up Android SDK
      uses: android-actions/setup-android@v2
        
    - name: Verify Java version
      run: |
        echo "=== Java Version Check ==="
        java -version
        echo "JAVA_HOME: $JAVA_HOME"
        echo "Java major version:"
        java -version 2>&1 | head -n 1 | cut -d'"' -f2 | cut -d'.' -f1
        echo "=== End Java Version Check ==="
        
    - name: Install Android SDK components
      run: |
        echo "=== Installing Android SDK Components ==="
        echo "Android SDK location: $ANDROID_HOME"
        
        # Accept licenses
        yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses
        
        # Install required components
        echo "Installing platform android-30..."
        $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "platforms;android-30"
        
        echo "Installing build tools 29.0.3..."
        $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "build-tools;29.0.3"
        
        echo "Installing platform tools..."
        $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "platform-tools"
        
        echo "=== End Installing Android SDK Components ==="
        
    - name: Verify Android SDK tools compatibility
      run: |
        echo "=== Android SDK Tools Check ==="
        echo "Android SDK location: $ANDROID_HOME"
        echo "Build tools available:"
        ls -la $ANDROID_HOME/build-tools/
        echo "Platforms available:"
        ls -la $ANDROID_HOME/platforms/
        echo "Platform tools available:"
        ls -la $ANDROID_HOME/platform-tools/
        echo "Checking build tools version compatibility:"
        $ANDROID_HOME/build-tools/29.0.3/aapt version
        echo "Checking aapt2 availability:"
        $ANDROID_HOME/build-tools/29.0.3/aapt2 version
        echo "=== End Android SDK Tools Check ==="
        
    - name: Verify build tools installation
      run: |
        echo "=== Verifying Build Tools Installation ==="
        echo "Checking for aapt:"
        ls -la $ANDROID_HOME/build-tools/29.0.3/aapt
        echo "Checking for aapt2:"
        ls -la $ANDROID_HOME/build-tools/29.0.3/aapt2
        echo "Checking for zipalign:"
        ls -la $ANDROID_HOME/build-tools/29.0.3/zipalign
        echo "Testing aapt version:"
        $ANDROID_HOME/build-tools/29.0.3/aapt version
        echo "Testing aapt2 version:"
        $ANDROID_HOME/build-tools/29.0.3/aapt2 version
        echo "=== End Verifying Build Tools Installation ==="
        
    - name: Debug Java and Android setup
      run: |
        echo "=== Environment Check ==="
        echo "Java version:"
        java -version
        echo "JAVA_HOME: $JAVA_HOME"
        echo "Android SDK location: $ANDROID_HOME"
        echo "Android SDK build-tools:"
        ls -la $ANDROID_HOME/build-tools/
        echo "Android SDK platforms:"
        ls -la $ANDROID_HOME/platforms/
        echo "=== Gradle Wrapper Test ==="
        ./gradlew --version
        echo "=== End Environment Check ==="
      

          
    - name: Make gradlew executable
      run: chmod +x gradlew
      
    - name: Test Gradle configuration
      run: |
        echo "=== Testing Gradle Configuration ==="
        echo "Gradle version:"
        ./gradlew --version
        echo "Available Android tasks:"
        ./gradlew tasks --all | grep -E "(android|assemble)" | head -5
        echo "=== End Testing Gradle Configuration ==="
      

      
    - name: Build APK
      run: |
        echo "=== Starting APK Build ==="
        echo "Using Java version:"
        java -version
        echo "Using Android build tools:"
        ls -la $ANDROID_HOME/build-tools/
        echo "Verifying aapt tool:"
        $ANDROID_HOME/build-tools/29.0.3/aapt version
        echo "Building APK..."
        ./gradlew android:assembleRelease
        echo "=== APK Build Complete ==="
      
    - name: Sign APK
      run: |
        # Create keystore for signing (for demo purposes - in production use proper keystore)
        keytool -genkey -v -keystore keystore.jks -keyalg RSA -keysize 2048 -validity 10000 -alias android -storepass android -keypass android -dname "CN=Android Debug,O=Android,C=US"
        
        # Sign the APK
        jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore keystore.jks android/build/outputs/apk/release/android-release-unsigned.apk android
        
        # Optimize APK
        $ANDROID_HOME/build-tools/29.0.3/zipalign -v 4 android/build/outputs/apk/release/android-release-unsigned.apk android/build/outputs/apk/release/Unlucky.apk
        
        # Verify APK was created
        ls -la android/build/outputs/apk/release/
      
    - name: Upload APK as artifact
      uses: actions/upload-artifact@v4
      with:
        name: Unlucky-APK
        path: android/build/outputs/apk/release/Unlucky.apk
        retention-days: 30
      
    - name: Get version
      id: get_version
      run: |
        if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
          echo "version=${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT
        else
          # Extract version from tag
          echo "version=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
        fi
        
    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: v${{ steps.get_version.outputs.version }}
        name: Release v${{ steps.get_version.outputs.version }}
        body: |
          Android APK for Unlucky game v${{ steps.get_version.outputs.version }}
          
          ## Installation
          1. Download the APK file
          2. Enable "Install from unknown sources" in your Android settings
          3. Install the APK
        files: android/build/outputs/apk/release/Unlucky.apk
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}