name: Modern Build - Current Stable Versions

on:
  push:
    branches: [ main, develop, update-game-name ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Java 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'gradle'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v2
        
    - name: Make gradlew executable
      run: chmod +x gradlew
      
    - name: Show environment
      run: |
        echo "=== ENVIRONMENT ==="
        echo "Java version:"
        java -version
        echo ""
        echo "Gradle version:"
        ./gradlew --version
        echo ""
        echo "Android SDK:"
        echo $ANDROID_HOME
        
    - name: Build Debug APK
      run: |
        echo "=== BUILDING DEBUG APK ==="
        ./gradlew :android:assembleDebug --stacktrace --info
        echo ""
        echo "Debug build completed!"
        
    - name: Build Release APK
      run: |
        echo "=== BUILDING RELEASE APK ==="
        ./gradlew :android:assembleRelease --stacktrace --info
        echo ""
        echo "Release build completed!"
        
    - name: Check APKs
      run: |
        echo "=== APK CHECK ==="
        echo "Looking for APK files:"
        find . -name "*.apk" -type f
        echo ""
        echo "Debug APK:"
        ls -la android/build/outputs/apk/debug/ 2>/dev/null || echo "No debug APK found"
        echo ""
        echo "Release APK:"
        ls -la android/build/outputs/apk/release/ 2>/dev/null || echo "No release APK found"
        
    - name: Upload Debug APK
      uses: actions/upload-artifact@v4
      if: hashFiles('android/build/outputs/apk/debug/*.apk') != ''
      with:
        name: K-pop-Monster-Hunter-Debug-APK
        path: android/build/outputs/apk/debug/*.apk
        retention-days: 90
        
    - name: Upload Release APK
      uses: actions/upload-artifact@v4
      if: hashFiles('android/build/outputs/apk/release/*.apk') != ''
      with:
        name: K-pop-Monster-Hunter-Release-APK
        path: android/build/outputs/apk/release/*.apk
        retention-days: 90