name: Simple Android Build

on:
  push:
    branches: [ main, develop, update-game-name ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Java 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v2
        
    - name: Make gradlew executable
      run: chmod +x gradlew
      
    - name: Show environment
      run: |
        echo "Java version:"
        java -version
        echo ""
        echo "Gradle version:"
        ./gradlew --version
        echo ""
        echo "Android SDK:"
        echo $ANDROID_HOME
        
    - name: Build Debug APK
      run: |
        ./gradlew :android:assembleDebug --stacktrace
      continue-on-error: true
      
    - name: Check for APK
      run: |
        echo "Looking for APK files..."
        find . -name "*.apk" -type f
        ls -la android/build/outputs/apk/debug/ 2>/dev/null || echo "No debug APK found"
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      if: hashFiles('android/build/outputs/apk/debug/*.apk') != ''
      with:
        name: K-pop-Monster-Hunter-APK
        path: android/build/outputs/apk/debug/*.apk