name: Test with Java 11

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Java 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v2
        
    - name: Make gradlew executable
      run: chmod +x gradlew
      
    - name: Show environment
      run: |
        echo "=== ENVIRONMENT ==="
        echo "Java version:"
        java -version
        echo ""
        echo "Gradle version:"
        ./gradlew --version
        echo ""
        echo "Android SDK:"
        echo $ANDROID_HOME
        
    - name: Test Gradle Parse
      run: |
        echo "=== GRADLE PARSE TEST ==="
        ./gradlew projects --stacktrace --info
        echo ""
        echo "Parse successful!"
        
    - name: Test Clean
      run: |
        echo "=== GRADLE CLEAN TEST ==="
        ./gradlew clean --stacktrace --info
        echo ""
        echo "Clean successful!"
        
    - name: Test Android Build
      run: |
        echo "=== ANDROID BUILD TEST ==="
        ./gradlew :android:assembleDebug --stacktrace --info
        echo ""
        echo "Android build successful!"
        
    - name: Check APK
      run: |
        echo "=== APK CHECK ==="
        find . -name "*.apk" -type f
        ls -la android/build/outputs/apk/debug/ 2>/dev/null || echo "No debug APK found"
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      if: hashFiles('android/build/outputs/apk/debug/*.apk') != ''
      with:
        name: K-pop-Monster-Hunter-Java11-APK
        path: android/build/outputs/apk/debug/*.apk