name: Test Project Parse

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Java 8
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'temurin'
        
    - name: Make gradlew executable
      run: chmod +x gradlew
      
    - name: Test Gradle Parse
      run: |
        echo "Testing if Gradle can parse the project..."
        ./gradlew projects
        echo ""
        echo "Testing if tasks can be listed..."
        ./gradlew tasks --all
        echo ""
        echo "Testing if dependencies can be resolved..."
        ./gradlew dependencies --configuration compileClasspath
      continue-on-error: true